name: Call Server API on branch creation

on: create

jobs:
  run-on-create:
    runs-on: ubuntu-latest
    steps:
      # needed to see code and branch name
      - name: Check out repository code
        uses: actions/checkout@v4
      # for now just echo branch name on creation
      - name: Report branch name
        run: echo "A branch or tag was created with the name ${{ github.ref_name }}."
      - name: Make API request on branch creation
        run: |
          curl --request POST \
          --url 'https://api.example.com/datahttps://22gwilliams.pythonanywhere.com/serverupdate' \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --data '{"branch": "${{ github.ref_name }}"}'
