name: Call Server API on branch creation

on: create

jobs:
  run-on-create:
    runs-on: ubuntu-latest
    steps:
      # needed to see code and branch name
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: View PR author
        run: echo "This PR is opened by ${{ github.event.pull_request.user.login }}."


      # uncomment when endpoint is ready
      # - name: Make API request on branch creation
      #   run: |
      #     curl --request POST \
      #     --url 'https://22gwilliams.pythonanywhere.com/serverupdate' \
      #     --header 'Accept: application/json' \
      #     --header 'Content-Type: application/json' \
      #     --data '{"branch": "${{ github.ref_name }}"}'
