name: Call server api when branch is merged

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      # get the head of the current branch
      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      # print out the code difference between main and the current branch
      # - name: print-diff
      #   shell: bash
      #   run: |
      #     git fetch origin main
      #     git diff --name-only HEAD^1 HEAD > mydiff
      #     echo "mydiff = "
      #     cat mydiffi
      # Uncomment api calls when endpoint is ready
      # - name: Make update request
      #   run: |
      #     curl --request POST \
      #       --url 'https://22gwilliams.pythonanywhere.com/merge' \
      #       --data '{"branch": "${{ github.ref_name }}", "diff": "$(cat mydiff)"}'