name: Call server api when PR is opened

on:
  pull_request:
    types:
      - opened

jobs:
  run-on-create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request HEAD
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: POST to /pr
        run: |
          curl --request POST https://trello-bored-bg8l.onrender.com/pr \
            --header 'Content-Type: application/json' \
            --header 'session-id: ${{ secrets.SESSION_ID }}' \
            --data "{\"username\": \"${{ github.event.pull_request.user.login }}\", \"pr-number\": \"${{ github.event.pull_request.number }}\"}"
