name: Call server api when PR is opened

on:
  pull_request_review:
    types:
      - submitted

jobs:
  run-on-create:
    runs-on: ubuntu-latest
    steps:
      # get the head of the current branch
      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      # print out the code difference between main and the current branch
      - name: print-diff
        shell: bash
        run: |
          git fetch origin main
          git diff origin/main..HEAD > mydiff
          echo "mydiff = "
          cat mydiff
      # for now just echo branch name on creation
      - name: Report branch name
        run: echo "A branch or tag was created with the name ${{ github.ref_name }}."
      - name: Make update request
        run: |
          curl --request POST \
            --url 'https://api.example.com/datahttps://22gwilliams.pythonanywhere.com/pr'
            --data '{"branch": "${{ github.ref_name }}", "diff": "$(cat mydiff)"}'